on:
  push:
    branches:
      - main

name: Build and release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: go build -mod vendor -v ./...
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13
        id: go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - name: Semantic versioning
        uses: go-semantic-release/action@v1
        id: semver
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          changelog-file: CHANGELOG.md
          allow-initial-development-versions: true
